### ISSUE TITLE
send payment 

### ISSUE THREAD

**Issue by sinobee** [RGB-Tools/rgb-lightning-node#28]
Steps I have taken:

Issue asset /issueassetlightning
Open channel /openchannel
Create invoice /lninvoice
Call the send payment API using the invoice
Close the channel
Everything works perfectly, but the asset amounts are not visible in the asset balance when I call the assetbalance API, even though I mined 6 blocks.

**Comment by nicbus** [comment]
Hi, what you have described is the behavior of the payment test so that's expected to work.

Can you please confirm the test is working by running `cargo test payment`?

A couple details:
- the issue API is called `/issueasset`
- did you close the channel cooperatively of did you force-close it?

Please report the logs of the operations you do, so hopefully we can better understand what might be going wrong.

**Comment by zoedberg** [comment]
At step 16 you reported
```
{
    "payments": [
        {
            "amt_msat": 3000000,
            "asset_amount": null,
            "asset_id": null,
            "payment_hash": "91dc144d67fa67e4c087a8b00ee974d07b5834b0d307db53f63b01f8e5fb1e35",
            "inbound": false,
            "status": "Succeeded"
        }
    ]
}
```
showing a payment that is in the correct status (`Succeeded`) but has no information about the transferred asset.
So this is a bug and I fixed that here: https://github.com/RGB-Tools/rust-lightning/commit/dacd467587a607a58209b047db15b8765f7e75fd (I've also improved the checks of the `payment` test in order to avoid future regressions, see https://github.com/RGB-Tools/rgb-lightning-node/commit/b9a44360ec03a5ab34701175c5349d309710e168)

> I suppose node 1 should have 900 and node 2 should have 100, but it looks like the assets were not transferred successfully.

Assets were being transferred correctly but information about RGB transfer was getting lost.
The spendable balance of node 1 is indicating that the assets from channel closure haven't been claimed yet. There is a periodic sweep task in RLN that runs once a day to claim on-chain funds after channel closures. When tests execute we set this time to 5 seconds (look for `interval_sweep_secs` in the code). Therefore I don't think there's a bug on channel closure. Maybe in the future we will allow users to specify a different interval for this task but for now if you just want to play with the node on regtest/testnet you can run the node with `cargo run --profile test` (this way the sweep task will execute every 5 seconds).

Closing this, feel free to re-open it if you don't think this has been solved
